- src/background.js
- src/manifest.json
Adicionando UOL, fechar issue #40
> Adicionando UOL #40

- src/LICENSE.txt
- src/background.js
- src/content.js
- src/manifest.json
Finalmente conseguimos burlar corretamente o GauchaZH.
Só falta fazer o merge desse pull request e lançar a versão estavel v5.0!
> Burla corretamente GauchaZH

- README.md
- src/background.js
- src/content.js
- src/manifest.json
Corrige issue #47 e atualiza README
> Corrige #47 e atualiza README

- src/background.js
- src/content-start.js
- src/content.js
- src/manifest.json
Atualiza site GauchaZH e corrige bug com SoundCloud.
> Atualiza GauchaZH

- webext/manifest.json
Esse sim resolve #69 
Descarta o #70
> Adiciona jsuol.com.br

- .eslintrc.yml
- README.md
- webext/background.js
- webext/content-start.js
- webext/content.js
- webext/manifest.json
- webext/options.html
- webext/options.js
Como o código sofreu grande refatoração, é necessário testar todos os sites novamente.
> Permitir a desativação por site na webextension

- .eslintrc.yml
- README.md
- webext/background.js
- webext/content-start.js
- webext/content.js
- webext/manifest.json
- webext/options.html
- webext/options.js
> Adiciona suporte ao Pioneiro

- userscript/burlesco.user.js
- webext/content.js
Current version is not working, now a div has to be removed
and the scroll must be set to visible
> Update burlesco for oglobo.globo.com

- webext/background.js
Esta PR também permite liberar scripts bloqueados globalmente de acordo com a URL da página. E resolve #89
> Corrige Acervo O Globo

- README.md
- webext/background.js
- webext/options.html
- webext/options.js
E @rodorgas, aproveitando, pq não havia a url do Santa Maria no manifesto da extensão?
Resolve #112
> Remove Diário de Santa Maria

- README.md
- userscript/burlesco.user.js
- webext/content.js
- webext/manifest.json
- webext/options.html
- webext/options.js
> Adiciona Bloomberg

- userscript/burlesco.user.js
- webext/background.js
- webext/content.js
- webext/manifest.json
- webext/options.js
> Adiciona Diário Popular (#117)

- userscript/burlesco.user.js
- webext/background.js
- webext/manifest.json
- webext/options.html
- webext/options.js
https://www.jornalvs.com.br/
resolve #140
> Adiciona Jornal VS (resolve #140)

- userscript/burlesco.user.js
- webext/background.js
- webext/manifest.json
- webext/options.html
- webext/options.js
> Adiciona BR18

- README.md
- userscript/burlesco.user.js
- webext/background.js
- webext/manifest.json
- webext/options.html
- webext/options.js
> Adiciona site El Tiempo (#150)

- userscript/burlesco.user.js
- webext/background.js
- webext/manifest.json
- webext/options.html
- webext/options.js
Artigo premium: https://www.haaretz.com/us-news/.premium-pittsburgh-shooting-highlights-vast-divide-between-liberal-u-s-jews-and-israel-1.6603040
Fonte: https://github.com/yuvadm/free-haaretz/
> Adiciona Haaretz

- userscript/burlesco.user.js
- webext/content-start.js
> Corrige GauchaZH

- README.md
- userscript/burlesco.user.js
- webext/content.js
- webext/manifest.json
- webext/options.html
- webext/options.js
Adicionar o site do diariodaregiao.com.br ao Burlesco.
> Add diariodaregiao.com.br

- webext/background.js
> Atualiza JOTA usando User-Agent do Google

- src/content-start.js
- src/manifest.json
- src/options.html
- src/options.js
> Adiciona Diário ABC Paulista

- src/background.js
- src/content-start.js
- src/manifest.json
> Adiciona suporte à Època (Globo)

- README.md
- src/content-start.js
- src/manifest.json
- src/options.html
- src/options.js
> Adiciona revista Crusoé

- src/background.js
> Bloqueia script quando também é inserido via requisição xhr

- src/content-start.js
> Corrige EM

- src/background.js
- src/manifest.json
> Corrige Folha de Londrina

- README.md
- src/content-start.js
- src/manifest.json
- src/options.html
- src/options.js
> Remove NEXO Jornal (Temporariamente)

- src/background.js
- src/content-start.js
- src/content.js
- src/manifest.json
- src/options.html
- src/options.js
> Nexo Jornal Corrigido

- .travis.yml
https://medium.com/@manjula.cse/how-to-stop-the-execution-of-travis-pipeline-if-script-exits-with-an-error-f0e5a43206bf
> Encerra o travis caso haja erro no building 

- src/background.js
> Corrige paywall da Revista Oeste

- src/background.js
> Corrige bloqueio do paywall do Estadão

- src/content.js
- src/manifest.json
Isso resolve as issues #345 e #342
> Elementos c/ "paywall" na classe são removidos no Valor Econômico

- src/background.js
- src/content-start.js
- src/manifest.json
> Atualiza GaúchaZH

- src/content-start.js
- src/manifest.json
crusoe.com.br > crusoe.uol.com.br
> Atualiza Crusoé
